configfile: "config.yaml"

include: "rules/simulate.smk"
include: "rules/align.smk",
include: "rules/varlociraptor.smk"
include: "rules/predictosaurus.smk"
include: "rules/alignoth.smk"

rule all:
    input:
        "results/variants.vcf",
        "results/mapped/reads.bam",
        "results/predictosaurus/scores.tsv",
        "results/observations/observations.bcf",
        "results/variant-calls/single.bcf",
        "results/alignoth/pileup.html",
